spring:
  profiles:
    active:
      - dev

---
server:
  port: 3366
spring:
  profiles: dev
  application:
    name: cloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

---
server:
  port: 3366
spring:
  profiles: test
  application:
    name: cloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
